name: Autopep8 Linter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install autopep8
      run: |
        python -m pip install --upgrade pip
        pip install autopep8

    - name: Run autopep8 on Python files
      run: |
        autopep8 --in-place --aggressive --aggressive --max-line-legth 100 **/*.py

    - name: Check for uncommitted changes
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        if [[ `git status --porcelain` ]]; then
          git add .
          git commit -m "Auto-format Python code with autopep8"
          git push
        else
          echo "No formatting changes required."
